/* eslint-disable no-console */
import Head from "next/head";
import { useSession } from "next-auth/react";
import PropTypes from "prop-types";
import { useEffect } from "react";
import NavigationBarButton from "../../components/NavigationBarButton";
import LoginWidget from "../components/LoginWidget";
import Homepage from "./homepage";

export default function MainApp({ setCurrentUser }) {
  const { data: session } = useSession();
  useEffect(() => {
    if (session) {
      fetch(`/api/login?email=${session.user.email}`)
        .then((response) => {
          if (!response.ok) {
            throw new Error("Network response was not ok");
          }
          return response.json();
        })
        .then((result) => {
          setCurrentUser(result[0]);
          console.log(session.user);
        })
        .catch((error) => console.log(error));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [session]);

  if (session) {
    return (
      <div style={{ display: "flex" }}>
        <NavigationBarButton />
        <Homepage />
      </div>
    );
  }
  return (
    <>
      <Head>
        <title>Server Practical</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            display: "flex",
            height: "100vh",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <div style={{ display: "grid", textAlign: "center" }}>
            <h1>Co-Lab History</h1>
            <LoginWidget />
            <h2>
              Welcome to our site! Please sign in to your Middlebury email to be
              one step closer to finding your next partner!
            </h2>
            <h3>No, not that kind ;)</h3>
          </div>
        </div>
      </main>
    </>
  );
}

MainApp.propTypes = {
  setCurrentUser: PropTypes.func,
};
