/* eslint-disable no-console */
import Head from "next/head";
import { useSession } from "next-auth/react";
import PropTypes from "prop-types";
import { useEffect } from "react";
import Image from "next/image";
import LoginWidget from "../components/LoginWidget";
import FeedPageComponent from "../../components/FeedpageComponent";
import middleburyLogo from "../../public/middleburyLogo.svg";

export default function MainApp({ setCurrentUser }) {
  const { data: session } = useSession();
  useEffect(() => {
    if (session) {
      fetch(`/api/login?email=${session.user.email}`)
        .then((response) => {
          if (!response.ok) {
            throw new Error("Network response was not ok");
          }
          return response.json();
        })
        .then((result) => {
          setCurrentUser(result[0]);
          console.log(session.user);
        })
        .catch((error) => console.log(error));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [session]);

  if (session) {
    return <FeedPageComponent />;
  }

  return (
    <>
      <Head>
        <title>Co-Lab History</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>{`
          html {
            height: 100%;
            margin: 0;
            background-image: linear-gradient(to right, #8FA8EA, #4E99EF);
            background-attachment: fixed;  // Ensures the background is fixed during scrolling
          }
          body {
            height: 100%;
            margin: 0;
            overflow: hidden;  // Prevents scrolling
          }
        `}</style>
      </Head>
      <main>
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            height: "100vh",
            alignItems: "center",
            justifyContent: "center",
            textAlign: "center",
            backgroundImage: "linear-gradient(to right, #8FA8EA, #4E99EF)",
          }}
        >
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              textAlign: "center",
              height: "60%",
              width: "310px",
              backgroundColor: "white",
            }}
          >
            <Image
              src={middleburyLogo}
              alt="logo"
              style={{ margin: " 35px auto", width: "100px", height: "100px" }}
            />
            <h1 style={{ margin: "15px" }}>Co-Lab History</h1>
            <p style={{ margin: "5px" }}>Authenticate with Google</p>
            <hr
              style={{
                width: "75%",
                height: "2px",
                border: "none",
                backgroundColor: "black",
                margin: "5px auto",
              }}
            />
            <LoginWidget size="large" />
          </div>
        </div>
      </main>
    </>
  );
}

MainApp.propTypes = {
  setCurrentUser: PropTypes.func,
};
